version: '3.8'
services:
  db:
    image: postgres
    container_name: articles-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: articles
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    container_name: articles-pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: 123
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes: 
  db:
  pgadmin:
